"""empty message

Revision ID: 01cd2dbe9ca0
Revises: c41c1dd20947
Create Date: 2023-07-17 17:21:18.076176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01cd2dbe9ca0'
down_revision = 'c41c1dd20947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('date', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_post_timestamp')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_post_timestamp', ['timestamp'], unique=False)
        batch_op.drop_column('date')
        batch_op.drop_column('event_name')

    # ### end Alembic commands ###
