"""empty message

Revision ID: 883fd50b0fbe
Revises: ff29cd61a16b
Create Date: 2023-07-17 16:02:39.747181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883fd50b0fbe'
down_revision = 'ff29cd61a16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_date'), ['date'], unique=True)
        batch_op.create_index(batch_op.f('ix_event_event_name'), ['event_name'], unique=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_date')
        batch_op.drop_index('ix_post_event_name')

    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('event_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.VARCHAR(length=140), nullable=True),
    sa.Column('date', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('ix_post_event_name', ['event_name'], unique=False)
        batch_op.create_index('ix_post_date', ['date'], unique=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_event_name'))
        batch_op.drop_index(batch_op.f('ix_event_date'))

    op.drop_table('event')
    # ### end Alembic commands ###
