"""empty message

Revision ID: ff29cd61a16b
Revises: ff85c55b0cef
Create Date: 2023-07-17 14:18:29.810737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff29cd61a16b'
down_revision = 'ff85c55b0cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('date', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_post_timestamp')
        batch_op.create_index(batch_op.f('ix_post_date'), ['date'], unique=True)
        batch_op.create_index(batch_op.f('ix_post_event_name'), ['event_name'], unique=True)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('body')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_level')
        batch_op.create_index(batch_op.f('ix_user_level'), ['level'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_level'))
        batch_op.create_index('ix_user_level', ['level'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_post_event_name'))
        batch_op.drop_index(batch_op.f('ix_post_date'))
        batch_op.create_index('ix_post_timestamp', ['timestamp'], unique=False)
        batch_op.drop_column('date')
        batch_op.drop_column('description')
        batch_op.drop_column('event_name')

    # ### end Alembic commands ###
