"""empty message

Revision ID: ff85c55b0cef
Revises: c14ab4e4e611
Create Date: 2023-07-10 16:52:16.261186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff85c55b0cef'
down_revision = 'c14ab4e4e611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_level'), ['level'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_level'))
        batch_op.drop_column('level')

    # ### end Alembic commands ###
